call installFile.bat gdata-analytics 2.1 gdata-analytics-2.1.jar
call installFile.bat gdata-analytics-meta 2.1 gdata-analytics-meta-2.1.jar
call installFile.bat gdata-appsforyourdomain 1.0 gdata-appsforyourdomain-1.0.jar
call installFile.bat gdata-appsforyourdomain-meta 1.0 gdata-appsforyourdomain-meta-1.0.jar
call installFile.bat gdata-base 1.0 gdata-base-1.0.jar
call installFile.bat gdata-blogger 2.0 gdata-blogger-2.0.jar
call installFile.bat gdata-blogger-meta 2.0 gdata-blogger-meta-2.0.jar
call installFile.bat gdata-books 1.0 gdata-books-1.0.jar
call installFile.bat gdata-books-meta 1.0 gdata-books-meta-1.0.jar
call installFile.bat gdata-calendar 2.0 gdata-calendar-2.0.jar
call installFile.bat gdata-calendar-meta 2.0 gdata-calendar-meta-2.0.jar
call installFile.bat gdata-client 1.0 gdata-client-1.0.jar
call installFile.bat gdata-client-meta 1.0 gdata-client-meta-1.0.jar
call installFile.bat gdata-codesearch 2.0 gdata-codesearch-2.0.jar
call installFile.bat gdata-codesearch-meta 2.0 gdata-codesearch-meta-2.0.jar
call installFile.bat gdata-contacts 3.0 gdata-contacts-3.0.jar
call installFile.bat gdata-contacts-meta 3.0 gdata-contacts-meta-3.0.jar
call installFile.bat gdata-core 1.0 gdata-core-1.0.jar
call installFile.bat gdata-docs 3.0 gdata-docs-3.0.jar
call installFile.bat gdata-docs-meta 3.0 gdata-docs-meta-3.0.jar
call installFile.bat gdata-finance 2.0 gdata-finance-2.0.jar
call installFile.bat gdata-finance-meta 2.0 gdata-finance-meta-2.0.jar
call installFile.bat gdata-gtt 2.0 gdata-gtt-2.0.jar
call installFile.bat gdata-gtt-meta 2.0 gdata-gtt-meta-2.0.jar
call installFile.bat gdata-health 2.0 gdata-health-2.0.jar
call installFile.bat gdata-health-meta 2.0 gdata-health-meta-2.0.jar
call installFile.bat gdata-maps 2.0 gdata-maps-2.0.jar
call installFile.bat gdata-maps-meta 2.0 gdata-maps-meta-2.0.jar
call installFile.bat gdata-media 1.0 gdata-media-1.0.jar
call installFile.bat gdata-photos 2.0 gdata-photos-2.0.jar
call installFile.bat gdata-photos-meta 2.0 gdata-photos-meta-2.0.jar
call installFile.bat gdata-projecthosting 2.1 gdata-projecthosting-2.1.jar
call installFile.bat gdata-projecthosting-meta 2.1 gdata-projecthosting-meta-2.1.jar
call installFile.bat gdata-sidewiki 2.0 gdata-sidewiki-2.0.jar
call installFile.bat gdata-sidewiki-meta 2.0 gdata-sidewiki-meta-2.0.jar
call installFile.bat gdata-sites 2.0 gdata-sites-2.0.jar
call installFile.bat gdata-sites-meta 2.0 gdata-sites-meta-2.0.jar
call installFile.bat gdata-spreadsheet 3.0 gdata-spreadsheet-3.0.jar
call installFile.bat gdata-spreadsheet-meta 3.0 gdata-spreadsheet-meta-3.0.jar
call installFile.bat gdata-webmastertools 2.0 gdata-webmastertools-2.0.jar
call installFile.bat gdata-webmastertools-meta 2.0 gdata-webmastertools-meta-2.0.jar
call installFile.bat gdata-youtube 2.0 gdata-youtube-2.0.jar
call installFile.bat gdata-youtube-meta 2.0 gdata-youtube-meta-2.0.jar
call installFile.bat google-collect 1.0-rc1 google-collect-1.0-rc1.jar
call mvn install:install-file -DgroupId=net.sourceforge.wurfl -DartifactId=wurlf-core -Dversion=1.0.1 -Dfile=wurfl-1.0.1.jar -Dpackaging=jar -DgeneratePom=true

